/**
 * Tests for handlePoolSubcommand: remote-target refusal and local lifecycle-port
 * resolution.
 *
 * Why these matter:
 *  - Remote refusal: enable/disable only mutate LOCAL config files. On a remote
 *    target the running proxy is never touched, so flipping the local flag and
 *    printing a hot-reload success message would lie. The command must refuse
 *    (exitCode 1) and leave the local pool flag untouched.
 *  - Port resolution: a user on a custom local.port (e.g. 9000) must have
 *    config-9000.yaml regenerated (the file the running proxy reads), not the
 *    default config.yaml.
 */
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { afterEach, beforeEach, describe, expect, it, spyOn } from 'bun:test';

import { handlePoolSubcommand } from '../pool-subcommand';
import {
  invalidateConfigCache as invalidateSharedConfigCache,
  mutateConfig,
} from '../../../config/config-loader-facade';

function createTestHome(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ccs-pool-subcommand-test-'));
  const ccsDir = path.join(dir, '.ccs');
  fs.mkdirSync(path.join(ccsDir, 'cliproxy', 'auth'), { recursive: true });
  fs.writeFileSync(path.join(ccsDir, 'config.yaml'), 'version: 1\n', 'utf8');
  return dir;
}

describe('handlePoolSubcommand', () => {
  let tempHome: string;
  let originalCcsHome: string | undefined;
  let logSpy: ReturnType<typeof spyOn>;
  let lines: string[];

  beforeEach(() => {
    tempHome = createTestHome();
    originalCcsHome = process.env.CCS_HOME;
    process.env.CCS_HOME = tempHome;
    invalidateSharedConfigCache();
    process.exitCode = 0;
    lines = [];
    logSpy = spyOn(console, 'log').mockImplementation((msg?: unknown) => {
      if (typeof msg === 'string') lines.push(msg);
    });
  });

  afterEach(() => {
    logSpy.mockRestore();
    process.exitCode = 0;
    if (originalCcsHome !== undefined) {
      process.env.CCS_HOME = originalCcsHome;
    } else {
      delete process.env.CCS_HOME;
    }
    fs.rmSync(tempHome, { recursive: true, force: true });
  });

  it('refuses --enable on a remote target, sets exitCode 1, and does not flip the local flag', async () => {
    mutateConfig((cfg) => {
      cfg.cliproxy_server = {
        remote: { enabled: true, host: '192.168.1.50', protocol: 'http' },
      };
    });
    invalidateSharedConfigCache();

    await handlePoolSubcommand(['--enable']);

    const output = lines.join('\n');
    expect(output).toContain('Remote proxy target detected');
    // Manual-config guidance is shown for the enable path
    expect(output).toContain('disable-cooling: false');
    expect(output).toContain('strategy: fill-first');
    expect(process.exitCode).toBe(1);

    // Local pool flag must remain untouched (not enabled).
    invalidateSharedConfigCache();
    const { loadOrCreateUnifiedConfig } = await import(
      `../../../config/config-loader-facade?poolremote=${Date.now()}`
    );
    const cfg = loadOrCreateUnifiedConfig();
    expect(cfg.cliproxy?.pool_routing?.enabled).not.toBe(true);

    // No local config.yaml should have been regenerated by the refused command.
    const cliproxyConfig = path.join(tempHome, '.ccs', 'cliproxy', 'config.yaml');
    expect(fs.existsSync(cliproxyConfig)).toBe(false);
  });

  it('refuses --disable on a remote target without the enable-only manual snippet', async () => {
    mutateConfig((cfg) => {
      cfg.cliproxy_server = {
        remote: { enabled: true, host: '192.168.1.50', protocol: 'http' },
      };
    });
    invalidateSharedConfigCache();

    await handlePoolSubcommand(['--disable']);

    const output = lines.join('\n');
    expect(output).toContain('Remote proxy target detected');
    // The disable refusal must NOT print the enable manual snippet
    expect(output).not.toContain('disable-cooling: false');
    expect(process.exitCode).toBe(1);
  });

  it('--enable on a local custom port regenerates config-<port>.yaml, not config.yaml', async () => {
    // Configure a custom local lifecycle port. resolveLifecyclePort() must pick
    // it up so the regenerated file matches what the running proxy reads.
    mutateConfig((cfg) => {
      cfg.cliproxy_server = { local: { port: 9000 } };
    });
    invalidateSharedConfigCache();

    await handlePoolSubcommand(['--enable']);

    const cliproxyDir = path.join(tempHome, '.ccs', 'cliproxy');
    const customConfig = path.join(cliproxyDir, 'config-9000.yaml');
    const defaultConfig = path.join(cliproxyDir, 'config.yaml');

    // The custom-port config file must be the one regenerated.
    expect(fs.existsSync(customConfig)).toBe(true);
    // The default-port config.yaml must NOT be written by a custom-port enable.
    expect(fs.existsSync(defaultConfig)).toBe(false);

    // And the regenerated file must carry the pool-on rails.
    const content = fs.readFileSync(customConfig, 'utf-8');
    expect(content).toContain('disable-cooling: false');
    expect(content).toContain('strategy: fill-first');
    // Success path must not flag a failure exit code.
    expect(process.exitCode).not.toBe(1);
  });
});
